#!/bin/bash
TOXCORE_PATH=${PWD}
TOXCORE_BUILD_PATH=${TOXCORE_PATH}/_build
TOXCORE_PREFIX_PATH=${TOXCORE_BUILD_PATH}/bin
LIBSODIUM_PATH=${TOXCORE_PATH}/third_party/
LIBSODIUM_BUILD_PATH=${LIBSODIUM_PATH}/libsodium
LIBSODIUM_PREFIX_PATH=${LIBSODIUM_BUILD_PATH}/bin

rm ${TOXCORE_BUILD_PATH} -R
rm ${LIBSODIUM_BUILD_PATH} -R
